using JNI.Core.Enums;
using System.Runtime.InteropServices;

namespace JNI.Core;

[StructLayout(LayoutKind.Sequential)]
public unsafe struct JNINativeInterface_
{
    public JNINativeInterface_() { }

    public void* reserved0, reserved1, reserved2, reserved3;

    public delegate* unmanaged<Env_*, JVersion> GetVersion;
    public delegate* unmanaged<Env_*, byte*, nint, byte*, int, nint> DefineClass;
    public delegate* unmanaged<Env_*, byte*, nint> FindClass;
    public delegate* unmanaged<Env_*, nint, nint> FromReflectedMethod;
    public delegate* unmanaged<Env_*, nint, nint> FromReflectedField;
    public delegate* unmanaged<Env_*, nint, nint, bool, nint> ToReflectedMethod;
    public delegate* unmanaged<Env_*, nint, nint> GetSuperclass;
    public delegate* unmanaged<Env_*, nint, nint, bool> IsAssignableFrom;
    public delegate* unmanaged<Env_*, nint, nint, bool, nint> ToReflectedField;
    public delegate* unmanaged<Env_*, nint, RetCode> Throw;
    public delegate* unmanaged<Env_*, nint, byte*, RetCode> ThrowNew;
    public delegate* unmanaged<Env_*, nint> ExceptionOccurred;
    public delegate* unmanaged<Env_*, void> ExceptionDescribe;
    public delegate* unmanaged<Env_*, void> ExceptionClear;
    public delegate* unmanaged<Env_*, byte*, void> FatalError;
    public delegate* unmanaged<Env_*, int, int> PushLocalFrame;
    public delegate* unmanaged<Env_*, nint, nint> PopLocalFrame;
    public delegate* unmanaged<Env_*, nint, nint> NewGlobalRef;
    public delegate* unmanaged<Env_*, nint, void> DeleteGlobalRef;
    public delegate* unmanaged<Env_*, nint, void> DeleteLocalRef;
    public delegate* unmanaged<Env_*, nint, nint, bool> IsSameObject;
    public delegate* unmanaged<Env_*, nint, nint> NewLocalRef;
    public delegate* unmanaged<Env_*, int, int> EnsureLocalCapacity;
    public delegate* unmanaged<Env_*, nint, nint> AllocObject;
    public delegate* unmanaged<Env_*, nint, nint, nint[], nint> NewObject;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, nint> NewObjectV;
    public delegate* unmanaged<Env_*, nint, nint, void*, nint> NewObjectA;
    public delegate* unmanaged<Env_*, nint, nint> GetObjectClass;
    public delegate* unmanaged<Env_*, nint, nint, bool> IsInstanceOf;
    public delegate* unmanaged<Env_*, nint, byte*, byte*, nint> GetMethodID;
    public delegate* unmanaged<Env_*, nint, nint, nint[], nint> CallObjectMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, nint> CallObjectMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, nint> CallObjectMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], bool> CallBooleanMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, bool> CallBooleanMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, bool> CallBooleanMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], byte> CallByteMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, byte> CallByteMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, byte> CallByteMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], ushort> CallCharMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, ushort> CallCharMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, ushort> CallCharMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], short> CallShortMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, short> CallShortMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, short> CallShortMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], int> CallIntMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, int> CallIntMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, int> CallIntMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], long> CallLongMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, long> CallLongMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, long> CallLongMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], float> CallFloatMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, float> CallFloatMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, float> CallFloatMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], double> CallDoubleMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, double> CallDoubleMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, double> CallDoubleMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], void> CallVoidMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, void> CallVoidMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, void> CallVoidMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint, nint[], nint> CallNonvirtualObjectMethod;
    public delegate* unmanaged<Env_*, nint, nint, nint, ArgIterator, nint> CallNonvirtualObjectMethodV;
    public delegate* unmanaged<Env_*, nint, nint, nint, void*, nint> CallNonvirtualObjectMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint, nint[], bool> CallNonvirtualBooleanMethod;
    public delegate* unmanaged<Env_*, nint, nint, nint, ArgIterator, bool> CallNonvirtualBooleanMethodV;
    public delegate* unmanaged<Env_*, nint, nint, nint, void*, bool> CallNonvirtualBooleanMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint, nint[], byte> CallNonvirtualByteMethod;
    public delegate* unmanaged<Env_*, nint, nint, nint, ArgIterator, byte> CallNonvirtualByteMethodV;
    public delegate* unmanaged<Env_*, nint, nint, nint, void*, byte> CallNonvirtualByteMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint, nint[], ushort> CallNonvirtualCharMethod;
    public delegate* unmanaged<Env_*, nint, nint, nint, ArgIterator, ushort> CallNonvirtualCharMethodV;
    public delegate* unmanaged<Env_*, nint, nint, nint, void*, ushort> CallNonvirtualCharMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint, nint[], short> CallNonvirtualShortMethod;
    public delegate* unmanaged<Env_*, nint, nint, nint, ArgIterator, short> CallNonvirtualShortMethodV;
    public delegate* unmanaged<Env_*, nint, nint, nint, void*, short> CallNonvirtualShortMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint, nint[], int> CallNonvirtualIntMethod;
    public delegate* unmanaged<Env_*, nint, nint, nint, ArgIterator, int> CallNonvirtualIntMethodV;
    public delegate* unmanaged<Env_*, nint, nint, nint, void*, int> CallNonvirtualIntMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint, nint[], long> CallNonvirtualLongMethod;
    public delegate* unmanaged<Env_*, nint, nint, nint, ArgIterator, long> CallNonvirtualLongMethodV;
    public delegate* unmanaged<Env_*, nint, nint, nint, void*, long> CallNonvirtualLongMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint, nint[], float> CallNonvirtualFloatMethod;
    public delegate* unmanaged<Env_*, nint, nint, nint, ArgIterator, float> CallNonvirtualFloatMethodV;
    public delegate* unmanaged<Env_*, nint, nint, nint, void*, float> CallNonvirtualFloatMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint, nint[], double> CallNonvirtualDoubleMethod;
    public delegate* unmanaged<Env_*, nint, nint, nint, ArgIterator, double> CallNonvirtualDoubleMethodV;
    public delegate* unmanaged<Env_*, nint, nint, nint, void*, double> CallNonvirtualDoubleMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint, nint[], void> CallNonvirtualVoidMethod;
    public delegate* unmanaged<Env_*, nint, nint, nint, ArgIterator, void> CallNonvirtualVoidMethodV;
    public delegate* unmanaged<Env_*, nint, nint, nint, void*, void> CallNonvirtualVoidMethodA;
    public delegate* unmanaged<Env_*, nint, byte*, byte*, nint> GetFieldID;
    public delegate* unmanaged<Env_*, nint, nint, nint> GetObjectField;
    public delegate* unmanaged<Env_*, nint, nint, bool> GetBooleanField;
    public delegate* unmanaged<Env_*, nint, nint, byte> GetByteField;
    public delegate* unmanaged<Env_*, nint, nint, ushort> GetCharField;
    public delegate* unmanaged<Env_*, nint, nint, short> GetShortField;
    public delegate* unmanaged<Env_*, nint, nint, int> GetIntField;
    public delegate* unmanaged<Env_*, nint, nint, long> GetLongField;
    public delegate* unmanaged<Env_*, nint, nint, float> GetFloatField;
    public delegate* unmanaged<Env_*, nint, nint, double> GetDoubleField;
    public delegate* unmanaged<Env_*, nint, nint, nint, void> SetObjectField;
    public delegate* unmanaged<Env_*, nint, nint, bool, void> SetBooleanField;
    public delegate* unmanaged<Env_*, nint, nint, byte, void> SetByteField;
    public delegate* unmanaged<Env_*, nint, nint, ushort, void> SetCharField;
    public delegate* unmanaged<Env_*, nint, nint, short, void> SetShortField;
    public delegate* unmanaged<Env_*, nint, nint, int, void> SetIntField;
    public delegate* unmanaged<Env_*, nint, nint, long, void> SetLongField;
    public delegate* unmanaged<Env_*, nint, nint, float, void> SetFloatField;
    public delegate* unmanaged<Env_*, nint, nint, double, void> SetDoubleField;
    public delegate* unmanaged<Env_*, nint, byte*, byte*, nint> GetStaticMethodID;
    public delegate* unmanaged<Env_*, nint, nint, nint[], nint> CallStaticObjectMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, nint> CallStaticObjectMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, nint> CallStaticObjectMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], bool> CallStaticBooleanMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, bool> CallStaticBooleanMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, bool> CallStaticBooleanMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], byte> CallStaticByteMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, byte> CallStaticByteMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, byte> CallStaticByteMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], ushort> CallStaticCharMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, ushort> CallStaticCharMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, ushort> CallStaticCharMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], short> CallStaticShortMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, short> CallStaticShortMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, short> CallStaticShortMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], int> CallStaticIntMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, int> CallStaticIntMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, int> CallStaticIntMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], long> CallStaticLongMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, long> CallStaticLongMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, long> CallStaticLongMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], float> CallStaticFloatMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, float> CallStaticFloatMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, float> CallStaticFloatMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], double> CallStaticDoubleMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, double> CallStaticDoubleMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, double> CallStaticDoubleMethodA;
    public delegate* unmanaged<Env_*, nint, nint, nint[], void> CallStaticVoidMethod;
    public delegate* unmanaged<Env_*, nint, nint, ArgIterator, void> CallStaticVoidMethodV;
    public delegate* unmanaged<Env_*, nint, nint, void*, void> CallStaticVoidMethodA;
    public delegate* unmanaged<Env_*, nint, byte*, byte*, nint> GetStaticFieldID;
    public delegate* unmanaged<Env_*, nint, nint, nint> GetStaticObjectField;
    public delegate* unmanaged<Env_*, nint, nint, bool> GetStaticBooleanField;
    public delegate* unmanaged<Env_*, nint, nint, byte> GetStaticByteField;
    public delegate* unmanaged<Env_*, nint, nint, ushort> GetStaticCharField;
    public delegate* unmanaged<Env_*, nint, nint, short> GetStaticShortField;
    public delegate* unmanaged<Env_*, nint, nint, int> GetStaticIntField;
    public delegate* unmanaged<Env_*, nint, nint, long> GetStaticLongField;
    public delegate* unmanaged<Env_*, nint, nint, float> GetStaticFloatField;
    public delegate* unmanaged<Env_*, nint, nint, double> GetStaticDoubleField;
    public delegate* unmanaged<Env_*, nint, nint, nint, void> SetStaticObjectField;
    public delegate* unmanaged<Env_*, nint, nint, bool, void> SetStaticBooleanField;
    public delegate* unmanaged<Env_*, nint, nint, byte, void> SetStaticByteField;
    public delegate* unmanaged<Env_*, nint, nint, ushort, void> SetStaticCharField;
    public delegate* unmanaged<Env_*, nint, nint, short, void> SetStaticShortField;
    public delegate* unmanaged<Env_*, nint, nint, int, void> SetStaticIntField;
    public delegate* unmanaged<Env_*, nint, nint, long, void> SetStaticLongField;
    public delegate* unmanaged<Env_*, nint, nint, float, void> SetStaticFloatField;
    public delegate* unmanaged<Env_*, nint, nint, double, void> SetStaticDoubleField;
    public delegate* unmanaged<Env_*, ushort*, int, nint> NewString;
    public delegate* unmanaged<Env_*, nint, int> GetStringLength;
    public delegate* unmanaged<Env_*, nint, bool*, ushort> GetStringChars;
    public delegate* unmanaged<Env_*, nint, ushort*, void> ReleaseStringChars;
    public delegate* unmanaged<Env_*, byte*, nint> NewStringUTF;
    public delegate* unmanaged<Env_*, nint, int> GetStringUTFLength;
    public delegate* unmanaged<Env_*, nint, bool*, byte*> GetStringUTFChars;
    public delegate* unmanaged<Env_*, nint, byte*, void> ReleaseStringUTFChars;
    public delegate* unmanaged<Env_*, nint, int> GetArrayLength;
    public delegate* unmanaged<Env_*, int, nint, nint, nint> NewObjectArray;
    public delegate* unmanaged<Env_*, nint, int, nint> GetObjectArrayElement;
    public delegate* unmanaged<Env_*, nint, int, nint, void> SetObjectArrayElement;
    public delegate* unmanaged<Env_*, int, nint> NewBooleanArray;
    public delegate* unmanaged<Env_*, int, nint> NewByteArray;
    public delegate* unmanaged<Env_*, int, nint> NewCharArray;
    public delegate* unmanaged<Env_*, int, nint> NewShortArray;
    public delegate* unmanaged<Env_*, int, nint> NewIntArray;
    public delegate* unmanaged<Env_*, int, nint> NewLongArray;
    public delegate* unmanaged<Env_*, int, nint> NewFloatArray;
    public delegate* unmanaged<Env_*, int, nint> NewDoubleArray;
    public delegate* unmanaged<Env_*, nint, bool*, bool*> GetBooleanArrayElements;
    public delegate* unmanaged<Env_*, nint, bool*, byte*> GetByteArrayElements;
    public delegate* unmanaged<Env_*, nint, bool*, ushort*> GetCharArrayElements;
    public delegate* unmanaged<Env_*, nint, bool*, short*> GetShortArrayElements;
    public delegate* unmanaged<Env_*, nint, bool*, int*> GetIntArrayElements;
    public delegate* unmanaged<Env_*, nint, bool*, long*> GetLongArrayElements;
    public delegate* unmanaged<Env_*, nint, bool*, float*> GetFloatArrayElements;
    public delegate* unmanaged<Env_*, nint, bool*, double*> GetDoubleArrayElements;
    public delegate* unmanaged<Env_*, nint, bool*, int, void> ReleaseBooleanArrayElements;
    public delegate* unmanaged<Env_*, nint, byte*, int, void> ReleaseByteArrayElements;
    public delegate* unmanaged<Env_*, nint, ushort*, int, void> ReleaseCharArrayElements;
    public delegate* unmanaged<Env_*, nint, short*, int, void> ReleaseShortArrayElements;
    public delegate* unmanaged<Env_*, nint, int*, int, void> ReleaseIntArrayElements;
    public delegate* unmanaged<Env_*, nint, long*, int, void> ReleaseLongArrayElements;
    public delegate* unmanaged<Env_*, nint, float*, int, void> ReleaseFloatArrayElements;
    public delegate* unmanaged<Env_*, nint, double*, int, void> ReleaseDoubleArrayElements;
    public delegate* unmanaged<Env_*, nint, int, int, bool*, void> GetBooleanArrayRegion;
    public delegate* unmanaged<Env_*, nint, int, int, byte*, void> GetByteArrayRegion;
    public delegate* unmanaged<Env_*, nint, int, int, ushort*, void> GetCharArrayRegion;
    public delegate* unmanaged<Env_*, nint, int, int, short*, void> GetShortArrayRegion;
    public delegate* unmanaged<Env_*, nint, int, int, int*, void> GetIntArrayRegion;
    public delegate* unmanaged<Env_*, nint, int, int, long*, void> GetLongArrayRegion;
    public delegate* unmanaged<Env_*, nint, int, int, float*, void> GetFloatArrayRegion;
    public delegate* unmanaged<Env_*, nint, int, int, double*, void> GetDoubleArrayRegion;
    public delegate* unmanaged<Env_*, nint, int, int, bool*, void> SetBooleanArrayRegion;
    public delegate* unmanaged<Env_*, nint, int, int, byte*, void> SetByteArrayRegion;
    public delegate* unmanaged<Env_*, nint, int, int, ushort*, void> SetCharArrayRegion;
    public delegate* unmanaged<Env_*, nint, int, int, short*, void> SetShortArrayRegion;
    public delegate* unmanaged<Env_*, nint, int, int, int*, void> SetIntArrayRegion;
    public delegate* unmanaged<Env_*, nint, int, int, long*, void> SetLongArrayRegion;
    public delegate* unmanaged<Env_*, nint, int, int, float*, void> SetFloatArrayRegion;
    public delegate* unmanaged<Env_*, nint, int, int, double*, void> SetDoubleArrayRegion;
    public delegate* unmanaged<Env_*, nint, NativeMethod_*, int, RetCode> RegisterNatives;
    public delegate* unmanaged<Env_*, nint, RetCode> UnregisterNatives;
    public delegate* unmanaged<Env_*, nint, RetCode> MonitorEnter;
    public delegate* unmanaged<Env_*, nint, RetCode> MonitorExit;
    public delegate* unmanaged<Env_*, JVM_**, int> GetJavaVM;
    public delegate* unmanaged<Env_*, nint, int, int, ushort*, void> GetStringRegion;
    public delegate* unmanaged<Env_*, nint, int, int, byte*, void> GetStringUTFRegion;
    public delegate* unmanaged<Env_*, nint, bool*, void*> GetPrimitiveArrayCritical;
    public delegate* unmanaged<Env_*, nint, void*, int, void> ReleasePrimitiveArrayCritical;
    public delegate* unmanaged<Env_*, nint, bool*, ushort*> GetStringCritical;
    public delegate* unmanaged<Env_*, nint, ushort*, void> ReleaseStringCritical;
    public delegate* unmanaged<Env_*, nint, nint> NewWeakGlobalRef;
    public delegate* unmanaged<Env_*, nint, void> DeleteWeakGlobalRef;
    public delegate* unmanaged<Env_*, bool> ExceptionCheck;
    public delegate* unmanaged<Env_*, void*, long, nint> NewDirectByteBuffer;
    public delegate* unmanaged<Env_*, nint, void*> GetDirectBufferAddress;
    public delegate* unmanaged<Env_*, nint, long> GetDirectBufferCapacity;
    public delegate* unmanaged<Env_*, nint, JObjRefType> GetObjectRefType;
}